---
functional:
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
  - Требование 3
  - Требование 4
implicit:
  - Требование 5
  - Требование 6
